In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import plotly.graph_objects as go

In [2]:
import pandas as pd

# download iris data and read it into a dataframe
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(url, names=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'])

In [32]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [4]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
fig = px.scatter(data_frame=df, x='SepalLengthCm',y='SepalWidthCm'
           ,color='Species',size='PetalLengthCm',template='seaborn',color_discrete_sequence=['#491D8B','#7D3AC1','#EB548C'],)

fig.update_layout(width=800, height=600,
                  xaxis=dict(color="#BF40BF"),
                 yaxis=dict(color="#BF40BF"))
fig.show()

In [41]:
X = X.to_numpy()

In [42]:
randomized_X = np.random.permutation(X.shape[0])

In [43]:
randomized_X

array([ 30,  97, 109, 118,  56, 110, 141, 148,  42, 128,  64, 117, 131,
       115, 126,  65,  95, 103, 136,  84,  40, 137, 127,  17, 113,  29,
       122, 108,  34, 106,  61, 149,   0, 132,  63,  58,  20,  78,  88,
        49,  43,  39,  51, 144,  22,  36,  37, 107,  87, 116, 145,  33,
        62, 105, 138, 143,  52,  23,  70, 112, 129,  31,  47,  75, 135,
        18,  98,  38,  91,   8,  28,   4,  10, 102,  67,   7,  54,  50,
        68,  44,  13,  25,  48,  12, 114, 124,  85,  92, 147,  14, 111,
        46,  32,  11,  90,  69,  80,  93,  26,  57, 139,  45,  66,  86,
        79, 121,  96,  35, 142, 104,  81, 134, 146,  27,  71,  89,  16,
        15,  55, 101,  77,   5, 133,  83,  76, 125,  53, 100,  21,  73,
        72,   1, 140,   9,  59,  19, 120,  99,  94, 130,   6,  24,  74,
        60, 123,  82,   3,  41, 119,   2], dtype=int32)

In [44]:
centroid_idx = randomized_X[:3]
centroids = X[centroid_idx]

In [45]:
centroids

array([[4.8, 3.1, 1.6, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3.6, 6.1, 2.5]])

In [46]:
points = np.array(())
for i in range(len(X)):
    cluster = np.argmin(np.linalg.norm((X[i] - centroids), axis=-1))
    points = np.append(points, cluster)


In [52]:
#X[points==0].mean(axis=0)
len(X[points==1])

69

In [54]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=X[points == 0, 0], y=X[points == 0, 1],
    mode='markers',marker_color='#DB4CB2',name='Iris-setosa'
))

fig.add_trace(go.Scatter(
    x=X[points == 1, 0], y=X[points == 1, 1],
    mode='markers',marker_color='#c9e9f6',name='Iris-versicolour'
))

fig.add_trace(go.Scatter(
    x=X[points == 2, 0], y=X[points == 2, 1],
    mode='markers',marker_color='#7D3AC1',name='Iris-virginica'
))

fig.add_trace(go.Scatter(
    x=centroids[:, 0], y=centroids[:,1],
    mode='markers',marker_color='#CAC9CD',marker_symbol=4,marker_size=13,name='Centroids'
))
fig.update_layout(template='plotly_dark',width=1000, height=500,)

In [55]:
centroids

array([[4.8, 3.1, 1.6, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [7.2, 3.6, 6.1, 2.5]])

In [56]:
for i in range(3):
    centroids[i] = X[points==i].mean(axis=0)

In [101]:
centroids

array([[[5.05555556, 3.16984127, 2.08730159, 0.5047619 ]],

       [[6.44691358, 3.01728395, 5.02469136, 1.73580247]],

       [[5.96666667, 2.33333333, 4.21666667, 1.23333333]]])

In [58]:
fig = go.Figure()
fig.add_trace(go.Scatter(
    x=X[points == 0,0], y=X[points == 0, 1],
    mode='markers',marker_color='#DB4CB2',name='Iris-setosa'
))

fig.add_trace(go.Scatter(
    x=X[points == 1, 0], y=X[points == 1, 1],
    mode='markers',marker_color='#c9e9f6',name='Iris-versicolour'
))

fig.add_trace(go.Scatter(
    x=X[points == 2, 0], y=X[points == 2, 1],
    mode='markers',marker_color='#7D3AC1',name='Iris-virginica'
))

fig.add_trace(go.Scatter(
    x=centroids[:, 0], y=centroids[:,1],
    mode='markers',marker_color='#CAC9CD',marker_symbol=4,marker_size=13,name='Centroids'
))
fig.update_layout(template='plotly_dark',width=1000, height=500,)