# ML Week 11: Neural Networks

In [33]:
import numpy as np
import scipy as sp

In [3]:
input = np.array([[1,2,3,4]])

In [73]:
weights = np.random.uniform(-1, 1, (4,4))

In [5]:
input

array([[1, 2, 3, 4]])

In [70]:
weights

array([[[-0.74080439, -0.90789329, -0.61695145],
        [-0.03193798, -0.20642207, -0.79717101],
        [-0.52182509,  0.36699943, -0.60689827],
        [ 0.73637816, -0.82090272, -0.51848546]],

       [[ 0.00671346, -0.90784492, -0.44454972],
        [ 0.06868263,  0.41652313,  0.40366755],
        [ 0.48137233, -0.8946618 ,  0.21453991],
        [ 0.21134526, -0.51769747,  0.24327779]],

       [[-0.52127222,  0.98822827,  0.50488059],
        [-0.95369362, -0.31819588,  0.10855305],
        [-0.93974328,  0.70134534, -0.63822559],
        [ 0.04972576, -0.00188874,  0.9304491 ]],

       [[ 0.89159535, -0.30054316,  0.20430502],
        [ 0.29164072, -0.98452369, -0.16871545],
        [-0.34345501,  0.20013464, -0.39797681],
        [-0.27150643,  0.3757629 , -0.53230813]]])

In [14]:
hidden_layer1 = input @ weights

In [16]:
hidden_layer1

array([[-1.14642607,  3.85617804, -3.56301691,  0.81203007]])

In [17]:
np.maximum(hidden_layer1,0)

array([[0.        , 3.85617804, 0.        , 0.81203007]])

In [81]:
weights = np.random.uniform(-1, 1, (4,4,3))

In [57]:
weights

array([[[ 0.68350188, -0.31759738,  0.49132052],
        [-0.77906551,  0.40326546,  0.97340144],
        [ 0.42487592,  0.64120617,  0.49182587],
        [-0.25698254, -0.40331628, -0.08301911]],

       [[-0.4584144 ,  0.30525895, -0.04119198],
        [ 0.45392726,  0.59486335,  0.02564594],
        [ 0.02087038,  0.0173279 , -0.34401778],
        [ 0.40714678, -0.71854625, -0.95624226]],

       [[ 0.28747549, -0.6025037 , -0.91312792],
        [-0.95133033, -0.8393383 ,  0.76899224],
        [-0.09396133, -0.43007482,  0.03274953],
        [-0.40700225, -0.32924777, -0.93974008]],

       [[ 0.10582345, -0.97128431,  0.16238084],
        [ 0.68832419,  0.74320676, -0.73625801],
        [-0.06658488, -0.92099703, -0.3047075 ],
        [-0.94971463, -0.6402286 ,  0.26453673]]])

In [ ]:
def forward_pass(input, weights):
    for i in range(weights.shape[2]):
        input = input @ weights[:,:,i]
        input = np.maximum(input,0)
    output = sp.special.softmax(input)
    output_class = np.argmax(output)
    return output_class

In [82]:
for i in range(50):
    print(forward_pass(np.random.uniform(-1,1,(1,4)), weights))

3
1
3
3
3
3
3
3
3
3
3
3
3
1
1
1
1
1
3
3
1
3
1
3
3
3
3
3
3
3
3
3
3
0
3
1
3
1
3
1
3
3
3
3
1
0
3
1
1
3


In [76]:
weights.shape

(4, 4, 3)

In [ ]:
# MLP = Multi-Layer Perceptron

from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)  # lbfgs = Limited-memory Broyden–Fletcher–Goldfarb–Shanno