# Hands-on Exercises in Machine Learning Applications in Digital Cultural Heritage
# Part II -- Computer Vision

### Tentative Schedule:
* 1 - Vectors and Matrices

* 2 - ANN

* 3 - Convolutions

* 4 - Convolutions 2

* 5 - Transformers intro?

* 6 - Classification

* 7 - Detection (YOLO?)

* 8 - Segmentation (SAM?)

* 9 - Autoencoders

* 10 - Autoencoders 2?

* 11 - Review

* 12 - Bias/Black Box?

* 13 - Cool stuff

* 14 - Student Presentations

# ML Week 10: Vectors and Matrices

In [1]:
import numpy as np

In [15]:
v = np.array([1,2,3,4])

In [24]:
M = np.array(
    [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    ]
)

In [12]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
v.T*M

array([[ 1,  4,  9, 16],
       [ 5, 12, 21, 32],
       [ 9, 20, 33, 48],
       [13, 28, 45, 64]])

In [21]:
w = np.array(
    [
    [1],
    [2],
    [3],
    [4]
    ]
)

In [22]:
w*M

array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36],
       [52, 56, 60, 64]])

In [25]:
w*v

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [31]:
np.random.rand(4,4)

array([[0.89798856, 0.79392535, 0.33796569, 0.59366088],
       [0.01078221, 0.25917636, 0.17521355, 0.08949211],
       [0.22178787, 0.40598186, 0.37119031, 0.3113445 ],
       [0.03588993, 0.44933611, 0.72177764, 0.37799877]])