In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("tools.csv")

In [4]:
df

Length  Width  Thickness  SharpEdgeWidth         Culture
0       5.1    3.5        1.4             0.2    Bear Culture
1       4.9    3.0        1.4             0.2    Bear Culture
2       4.7    3.2        1.3             0.2    Bear Culture
3       4.6    3.1        1.5             0.2    Bear Culture
4       5.0    3.6        1.4             0.2    Bear Culture
..      ...    ...        ...             ...             ...
145     6.7    3.0        5.2             2.3  Beaver Culture
146     6.3    2.5        5.0             1.9  Beaver Culture
147     6.5    3.0        5.2             2.0  Beaver Culture
148     6.2    3.4        5.4             2.3  Beaver Culture
149     5.9    3.0        5.1             1.8  Beaver Culture

[150 rows x 5 columns]

In [5]:
X = df.iloc[:,:-1].to_numpy()
Y = df.iloc[:,-1].to_numpy()

In [8]:
Y_strings = Y

In [9]:
from sklearn.preprocessing import LabelEncoder

In [11]:
Y = LabelEncoder().fit_transform(Y)

In [12]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
Y_strings

array(['Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Bear Culture', 'Bear Culture',
       'Bear Culture', 'Bear Culture', 'Owl Culture', 'Owl Culture',
       'Owl Culture', 'Owl Culture', 'Owl Culture', 'Owl Culture',
       'Owl 

In [21]:
label_dict = {}
for i in range(len(Y)):
    label_dict[int(Y[i])] = Y_strings[i]

In [18]:
label_dict

{0: 'Bear Culture', 2: 'Owl Culture', 1: 'Beaver Culture'}

In [23]:
label_dict[1]

'Beaver Culture'

In [25]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
gini(Y)

0.6666666666666667

In [35]:
def gini(Y):
    gini = 0
    for y in set(Y):
        probability = len(Y[Y==y])/len(Y)
        gini += probability * (1 - probability)
    return gini

In [50]:
set(X[:,1])

{np.float64(2.0),
 np.float64(2.2),
 np.float64(2.3),
 np.float64(2.4),
 np.float64(2.5),
 np.float64(2.6),
 np.float64(2.7),
 np.float64(2.8),
 np.float64(2.9),
 np.float64(3.0),
 np.float64(3.1),
 np.float64(3.2),
 np.float64(3.3),
 np.float64(3.4),
 np.float64(3.5),
 np.float64(3.6),
 np.float64(3.7),
 np.float64(3.8),
 np.float64(3.9),
 np.float64(4.0),
 np.float64(4.1),
 np.float64(4.2),
 np.float64(4.4)}

In [52]:
for i in sorted(set(X[:,1]))[1:]:
    print(i)

2.2
2.3
2.4
2.5
2.6
2.7
2.8
2.9
3.0
3.1
3.2
3.3
3.4
3.5
3.6
3.7
3.8
3.9
4.0
4.1
4.2
4.4


In [80]:
def find_best_split(X, Y):
    best_col = None
    best_split = None
    best_gini = gini(Y)
    for col in range(X.shape[1]):
        for x in sorted(set(X[:,col]))[1:]:
            left_split = Y[X[:,col] < x]
            right_split = Y[X[:,col] >= x]
            new_gini = (len(left_split)/len(Y))*gini(left_split) + (len(right_split)/len(Y))*gini(right_split)
            if new_gini < best_gini:
                best_gini = new_gini
                best_col = col
                best_split = x
    return best_col, float(best_split)

In [77]:
find_best_split(X, Y)

0 4.4 0.6621923937360179
0 4.5 0.6484018264840182
0 4.6 0.6436781609195403
0 4.7 0.624113475177305
0 4.8 0.6139088729016785
0 4.9 0.5870646766169155
0 5.0 0.5812026515151516
0 5.1 0.5467867231638418
0 5.2 0.49824718430670545
0 5.3 0.48211640211640205
0 5.4 0.47421962095875136
0 5.5 0.4389063317634746
2 1.7 0.389937106918239
2 1.9 0.35294117647058826
2 3.0 0.3333333333333333


(2, 3.0)

In [53]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [83]:
def decision_tree(X,Y,level=0):
    if len(set(Y)) == 1:
        print("Leaf node reached with value of " + str(Y[0]))
        return None
    else:
        best_col, best_split = find_best_split(X,Y)
        print(level, best_col, best_split)

        left_X = X[X[:,best_col] < best_split]
        left_Y = Y[X[:,best_col] < best_split]

        right_X = X[X[:,best_col] >= best_split]
        right_Y = Y[X[:,best_col] >= best_split]
        
        print("going left")
        decision_tree(left_X, left_Y, level = level+1)
        print("going right")
        decision_tree(right_X, right_Y, level = level+1)
        return None

In [84]:
decision_tree(X,Y)

0 2 3.0
going left
Leaf node reached with value of 0
going right
1 3 1.8
going left
2 2 5.0
going left
3 3 1.7
going left
Leaf node reached with value of 2
going right
Leaf node reached with value of 1
going right
3 3 1.6
going left
Leaf node reached with value of 1
going right
4 0 7.2
going left
Leaf node reached with value of 2
going right
Leaf node reached with value of 1
going right
2 2 4.9
going left
3 0 6.0
going left
Leaf node reached with value of 2
going right
Leaf node reached with value of 1
going right
Leaf node reached with value of 1


In [85]:
def my_tree(x):
    if x[2] < 3.0:  # Level 0
        return 0
    else:
        if x[3] < 1.8:  # Level 1
            if x[2] < 5.0:  # Level 2
                if x[3] < 1.7:  # Level 3
                    return 2
                else:
                    return 1
            else:
                if x[3] < 1.6:  # Level 3
                    return 1
                else:
                    if x[0] < 7.2:  # Level 4
                        return 2
                    else:
                        return 1
        else:
            if x[2] < 4.9:  # Level 2
                if x[0] <  6.0:  # Level 3
                    return 2
                else:
                    return 1
            else:
                return 1

In [88]:
int_class = my_tree([3,5.2,3.7,2])
label_dict[int_class]

'Owl Culture'